/**
 * Verified Development & Demo Workers Seed
 * (Clearly marked as TEST / DEMO DATA for development & staging environments)
 */

const SEEDED_DEV_WORKERS = [
  {
    workerId: "w_ramanand_kumar",
    name: "Ramanand Kumar",
    occupation: "Master House Painter & Wall Texture Specialist",
    category: "painter",
    phone: "6203637790",
    rating: 4.9,
    reviewsCount: 142,
    jobsCompleted: 165,
    trustScore: 99,
    experience: "4 years",
    location: "Sector 17, Chandigarh",
    visitingFee: 149,
    hourlyRate: 349,
    avatarUrl: "/workers/ramanand-kumar.png",
    isOnline: true,
    isVerified: true,
    skills: ["Interior Emulsion Painting", "Exterior Weathercoat", "Wall Putty & Primer", "Artistic Texture Designing", "Waterproofing & Seepage Fix"],
    emergencySupported: true,
    isDemoData: true
  },
  {
    workerId: "w_bike_1",
    name: "Raj Kumar",
    occupation: "Senior Bike & Scooter Mechanic",
    category: "bike_repair",
    phone: "+91 98765 11001",
    rating: 4.9,
    reviewsCount: 145,
    jobsCompleted: 210,
    trustScore: 98,
    experience: "7 years",
    location: "Sector 17, Chandigarh",
    visitingFee: 149,
    hourlyRate: 249,
    isOnline: true,
    isVerified: true,
    skills: ["Bike Engine Overhaul", "Carburetor Tuning", "Clutch & Brake Repair", "Puncture SOS", "Activa Servicing"],
    emergencySupported: true,
    isDemoData: true
  },
  {
    workerId: "w_car_1",
    name: "Ramanand",
    occupation: "Master Automobile & Car Diagnostic Specialist",
    category: "mechanic_car",
    phone: "+91 98765 11002",
    rating: 4.9,
    reviewsCount: 184,
    jobsCompleted: 260,
    trustScore: 99,
    experience: "8 years",
    location: "Sector 17, Chandigarh",
    visitingFee: 199,
    hourlyRate: 399,
    isOnline: true,
    isVerified: true,
    skills: ["Engine Diagnostics", "Brake Overhaul", "Radiator Coolant", "Highway Breakdown SOS", "Clutch Replacement"],
    emergencySupported: true,
    isDemoData: true
  },
  {
    workerId: "w_plumb_1",
    name: "Vikram Sharma",
    occupation: "Certified Master Plumber",
    category: "plumber",
    phone: "+91 98765 11003",
    rating: 4.8,
    reviewsCount: 112,
    jobsCompleted: 140,
    trustScore: 95,
    experience: "6 years",
    location: "Sector 17, Chandigarh",
    visitingFee: 149,
    hourlyRate: 299,
    isOnline: true,
    isVerified: true,
    skills: ["Concealed Pipe Leaks", "Tap & Valve Repair", "Drain Blockage", "Water Motor Booster", "Sanitaryware"],
    emergencySupported: true,
    isDemoData: true
  },
  {
    workerId: "w_elec_1",
    name: "Amit Patel",
    occupation: "Licensed Electrical Technician",
    category: "electrician",
    phone: "+91 98765 11004",
    rating: 4.9,
    reviewsCount: 195,
    jobsCompleted: 230,
    trustScore: 97,
    experience: "7 years",
    location: "Sector 17, Chandigarh",
    visitingFee: 149,
    hourlyRate: 349,
    isOnline: true,
    isVerified: true,
    skills: ["Short Circuit Recovery", "MCB Trip Repair", "House Wiring", "Ceiling Fan", "Inverter Setup"],
    emergencySupported: true,
    isDemoData: true
  },
  {
    workerId: "w_ac_1",
    name: "Deepak Kumar",
    occupation: "HVAC & AC Service Specialist",
    category: "ac",
    phone: "+91 98765 11005",
    rating: 4.7,
    reviewsCount: 92,
    jobsCompleted: 115,
    trustScore: 93,
    experience: "5 years",
    location: "Sector 17, Chandigarh",
    visitingFee: 199,
    hourlyRate: 399,
    isOnline: true,
    isVerified: true,
    skills: ["Jet Pump Cleaning", "Gas Leak Detection", "Compressor PCB Repair", "Cooling Optimization"],
    emergencySupported: false,
    isDemoData: true
  },
  {
    workerId: "w_ro_1",
    name: "Suresh Mehra",
    occupation: "Water Purifier & RO Technician",
    category: "ro_repair",
    phone: "+91 98765 11006",
    rating: 4.8,
    reviewsCount: 78,
    jobsCompleted: 88,
    trustScore: 94,
    experience: "4 years",
    location: "Sector 17, Chandigarh",
    visitingFee: 149,
    hourlyRate: 249,
    isOnline: true,
    isVerified: true,
    skills: ["RO Membrane Change", "Filter Replacement", "TDS Calibration", "Booster Pump"],
    emergencySupported: false,
    isDemoData: true
  },
  {
    workerId: "w_comp_1",
    name: "Nitin Verma",
    occupation: "Hardware & Laptop Engineer",
    category: "computer_repair",
    phone: "+91 98765 11007",
    rating: 4.9,
    reviewsCount: 130,
    jobsCompleted: 175,
    trustScore: 96,
    experience: "6 years",
    location: "Sector 17, Chandigarh",
    visitingFee: 149,
    hourlyRate: 349,
    isOnline: true,
    isVerified: true,
    skills: ["Blue Screen Recovery", "SSD Upgrade", "RAM Expansion", "Hinge Repair", "Keyboard Replacement"],
    emergencySupported: false,
    isDemoData: true
  }
];

module.exports = { SEEDED_DEV_WORKERS };
